CREATE TABLE IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    uids VARCHAR (300) NOT NULL,
    username VARCHAR (100) NOT NULL,
    pass VARCHAR(300) NOT NULL,
    profile JSON DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE `users` 
ADD  column if not exists `email` VARCHAR(300) NOT NULL AFTER `uids`;


CREATE TABLE IF NOT EXISTS currency(
    id INT AUTO_INCREMENT PRIMARY KEY,
    currency_name ENUM('NGN', 'USD', 'YEN', 'GHC', 'ZAR', 'EUR', 'JPY', 'CHF', 'AUD', 'GBP') DEFAULT 'USD',
    currency_amount DECIMAL (10,2) DEFAULT 0.00,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallet(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    currency_value INT NOT NULL,
    amount DECIMAL (10,2) DEFAULT 0.00,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (currency_value) REFERENCES currency(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS deposit(
    id INT AUTO_INCREMENT PRIMARY KEY,
    payment_code VARCHAR (500) NOT NULL,
    amount DECIMAL (10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);