name: 🚀 Auto FTP Deploy to shoplenca
on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload Entire Repo to /home/moninqnb/xgod
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v4

      - name: 🚀 Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}

          local-dir: ./
          server-dir: /home/moninqnb/xgod

          # FULL overwrite deployment
          dangerous-clean-slate: true

          # FOLDERS/FILES THAT MUST NOT BE TOUCHED
          exclude: |
            upload/**
            upload/*
            .git/**
            .github/**
            README.md
